version: '3.8'

services:
  backend:
    build: .
    container_name: mev-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - SOLANA_RPC_URL=${SOLANA_RPC_URL}
      - SOLANA_NETWORK=${SOLANA_NETWORK}
      - JITO_BLOCK_ENGINE_URL=${JITO_BLOCK_ENGINE_URL}
      - JITO_AUTH_KEYPAIR=${JITO_AUTH_KEYPAIR}
    networks:
      - mev-network

  frontend:
    build: ./frontend
    container_name: mev-frontend
    restart: unless-stopped
    ports:
      - "3001:3000"
    depends_on:
      - backend
    networks:
      - mev-network

networks:
  mev-network:
    driver: bridge
