-- Module 2: Understanding Jito (5 sections)
INSERT INTO module_content (module_id, section_order, section_type, title, content) VALUES
(2, 1, 'text', 'What is Jito?', '{"text": "Jito is a MEV infrastructure protocol for Solana that enables validators to capture MEV rewards while maintaining network decentralization. It provides a marketplace where searchers can submit transaction bundles to validators.", "keyPoints": ["Jito enables atomic transaction bundles on Solana", "Validators earn additional revenue from MEV", "Searchers get guaranteed execution or revert", "Reduces network spam from failed MEV attempts"]}'),
(2, 2, 'text', 'How Jito Works', '{"text": "Jito operates through a modified Solana validator client that accepts bundles from searchers. These bundles are atomic - either all transactions execute or none do.", "keyPoints": ["Searchers submit bundles via Jito Block Engine", "Validators run Jito-Solana client", "Bundles compete via tips to validators", "Failed bundles don''t consume blockspace"]}'),
(2, 3, 'text', 'Jito vs Regular Validators', '{"comparison": [{"aspect": "MEV Capture", "regular": "Limited", "jito": "Full MEV capture", "benefit": "Higher validator revenue"}, {"aspect": "Bundle Support", "regular": "No", "jito": "Yes", "benefit": "Atomic execution guarantees"}, {"aspect": "Searcher Access", "regular": "Public mempool only", "jito": "Direct bundle submission", "benefit": "Better execution rates"}], "keyPoints": ["Jito validators earn 5-15% more revenue", "Bundle success rates are 3-5x higher", "Reduced network congestion from failed attempts"]}'),
(2, 4, 'text', 'Benefits for Searchers', '{"text": "Searchers benefit from guaranteed atomic execution, higher success rates, and protection from front-running by other bots.", "keyPoints": ["Atomic bundles prevent partial execution", "Higher success rates (60-80% vs 20-40%)", "Protection from sandwich attacks", "Lower overall costs due to fewer failed attempts"]}'),
(2, 5, 'text', 'Jito Economics', '{"text": "Jito creates a sustainable MEV economy where validators, searchers, and the network all benefit. Tips flow from searchers to validators based on bundle value.", "keyPoints": ["Searchers pay tips (0.1-5% of MEV)", "Validators earn tips + block rewards", "Network benefits from reduced spam", "Transparent and competitive marketplace"]}');

INSERT INTO quizzes (module_id, title, passing_score, questions) VALUES
(2, 'Jito Knowledge Check', 80, '[
  {"id": 1, "question": "What does Jito enable on Solana?", "options": ["Faster transactions", "Atomic transaction bundles", "Lower fees", "More validators"], "correct": 1, "explanation": "Jito enables atomic transaction bundles that either fully execute or fully revert."},
  {"id": 2, "question": "How much more revenue can Jito validators earn?", "options": ["1-3%", "5-15%", "20-30%", "50%+"], "correct": 1, "explanation": "Jito validators typically earn 5-15% more revenue from MEV tips."},
  {"id": 3, "question": "What happens if one transaction in a Jito bundle fails?", "options": ["Only that transaction reverts", "The entire bundle reverts", "It retries automatically", "Other transactions still execute"], "correct": 1, "explanation": "Jito bundles are atomic - if any transaction fails, the entire bundle reverts."},
  {"id": 4, "question": "What do searchers pay to validators for bundle inclusion?", "options": ["Gas fees only", "Tips", "Staking rewards", "Nothing extra"], "correct": 1, "explanation": "Searchers pay tips to validators based on the value of their MEV opportunity."},
  {"id": 5, "question": "How do Jito bundle success rates compare to regular transactions?", "options": ["Same", "Slightly lower", "3-5x higher", "10x higher"], "correct": 2, "explanation": "Jito bundles have 3-5x higher success rates due to atomic execution and direct validator submission."},
  {"id": 6, "question": "What is the main benefit of Jito for the Solana network?", "options": ["Faster blocks", "Reduced spam from failed MEV attempts", "More validators", "Lower fees"], "correct": 1, "explanation": "Jito reduces network spam because failed bundles don''t consume blockspace."}
]');

-- Module 3: Arbitrage Strategies (6 sections)
INSERT INTO module_content (module_id, section_order, section_type, title, content) VALUES
(3, 1, 'text', 'Arbitrage Fundamentals', '{"text": "Arbitrage is the practice of profiting from price differences of the same asset across different markets. On Solana, this typically involves DEXs like Raydium, Orca, and Serum.", "keyPoints": ["Buy low on one DEX, sell high on another", "Profit is the price difference minus costs", "Opportunities exist due to market inefficiencies", "Speed is critical - opportunities disappear quickly"]}'),
(3, 2, 'text', 'Types of Arbitrage', '{"text": "Several arbitrage strategies exist on Solana, each with different risk/reward profiles.", "examples": [{"type": "Cross-DEX Arbitrage", "description": "Trade between Raydium and Orca when prices diverge. Example: SOL is $100 on Raydium, $101 on Orca."}, {"type": "Triangular Arbitrage", "description": "Trade through 3+ pairs to exploit rate inconsistencies. Example: SOL→USDC→RAY→SOL for net profit."}, {"type": "Statistical Arbitrage", "description": "Use historical correlations to predict mean reversion opportunities."}]}'),
(3, 3, 'text', 'Calculating Profitability', '{"text": "Profitable arbitrage requires careful calculation of all costs including gas, slippage, and price impact.", "keyPoints": ["Gross Profit = Sell Price - Buy Price", "Net Profit = Gross Profit - Gas - Slippage - Price Impact", "Minimum viable profit typically 0.1-0.5%", "Must execute within 1-2 blocks to avoid price changes"]}'),
(3, 4, 'text', 'Risk Factors', '{"text": "Arbitrage carries several risks that can turn profitable opportunities into losses.", "keyPoints": ["Price movement during execution", "Slippage on large trades", "Failed transactions consuming gas", "Competition from other bots", "Smart contract risks"]}'),
(3, 5, 'text', 'Execution Strategy', '{"text": "Successful arbitrage requires optimal execution strategy including route selection, timing, and bundle construction.", "keyPoints": ["Use Jito bundles for atomic execution", "Split large trades to minimize slippage", "Monitor mempool for competing transactions", "Set appropriate slippage tolerance (0.5-2%)"]}'),
(3, 6, 'text', 'Advanced Techniques', '{"text": "Professional arbitrageurs use sophisticated techniques to maximize profits and minimize risks.", "keyPoints": ["Flash loans for capital efficiency", "Multi-hop routing for better prices", "Statistical models for opportunity prediction", "Custom RPC nodes for faster execution"]}');

INSERT INTO quizzes (module_id, title, passing_score, questions) VALUES
(3, 'Arbitrage Mastery Quiz', 80, '[
  {"id": 1, "question": "What is arbitrage?", "options": ["Buying and holding assets", "Profiting from price differences across markets", "Lending crypto for interest", "Mining cryptocurrency"], "correct": 1, "explanation": "Arbitrage is profiting from price differences of the same asset across different markets."},
  {"id": 2, "question": "What is the formula for net arbitrage profit?", "options": ["Sell Price - Buy Price", "Gross Profit - All Costs", "Buy Price - Sell Price", "Revenue - Expenses"], "correct": 1, "explanation": "Net profit = Gross Profit - Gas - Slippage - Price Impact."},
  {"id": 3, "question": "What is triangular arbitrage?", "options": ["Trading 3 times per day", "Trading through 3+ pairs for profit", "Using 3 DEXs", "Trading 3 different tokens"], "correct": 1, "explanation": "Triangular arbitrage trades through 3+ pairs to exploit rate inconsistencies."},
  {"id": 4, "question": "What is the typical minimum viable arbitrage profit?", "options": ["0.01%", "0.1-0.5%", "5-10%", "20%+"], "correct": 1, "explanation": "Minimum viable profit is typically 0.1-0.5% to cover all costs."},
  {"id": 5, "question": "Why use Jito bundles for arbitrage?", "options": ["Lower fees", "Atomic execution", "Faster transactions", "Higher profits"], "correct": 1, "explanation": "Jito bundles provide atomic execution - either all trades succeed or all revert."},
  {"id": 6, "question": "What is slippage?", "options": ["Transaction fees", "Price difference from expected", "Network congestion", "Validator tips"], "correct": 1, "explanation": "Slippage is the difference between expected and actual execution price."},
  {"id": 7, "question": "How quickly must arbitrage execute?", "options": ["Within 1 hour", "Within 10 minutes", "Within 1-2 blocks", "Anytime"], "correct": 2, "explanation": "Arbitrage must execute within 1-2 blocks (under 1 second) to avoid price changes."},
  {"id": 8, "question": "What is a flash loan used for in arbitrage?", "options": ["Long-term investment", "Capital efficiency", "Paying gas fees", "Staking"], "correct": 1, "explanation": "Flash loans provide capital efficiency by borrowing funds within a single transaction."}
]');

-- Module 4: Liquidation Hunting (6 sections)
INSERT INTO module_content (module_id, section_order, section_type, title, content) VALUES
(4, 1, 'text', 'Liquidation Basics', '{"text": "Liquidations occur when a borrower''s collateral value falls below the required threshold on lending protocols. Liquidators can repay the debt and claim collateral at a discount.", "keyPoints": ["Lending protocols require overcollateralization", "Health factor < 1.0 triggers liquidation", "Liquidators earn 5-15% bonus", "Speed is critical - first liquidator wins"]}'),
(4, 2, 'text', 'Health Factor Calculation', '{"text": "Health factor determines if a position can be liquidated. It''s calculated as: (Collateral Value × Liquidation Threshold) / Borrowed Value", "keyPoints": ["Health Factor > 1.0 = Safe", "Health Factor = 1.0 = At risk", "Health Factor < 1.0 = Can be liquidated", "Monitor positions approaching 1.0"]}'),
(4, 3, 'text', 'Finding Opportunities', '{"text": "Liquidation opportunities are found by monitoring lending protocols for positions with declining health factors.", "keyPoints": ["Query lending protocol APIs", "Monitor price feeds for collateral assets", "Track positions near liquidation threshold", "Set up alerts for health factor < 1.05"]}'),
(4, 4, 'text', 'Liquidation Mechanics', '{"text": "Executing a liquidation involves repaying part or all of the debt and receiving collateral plus a bonus.", "keyPoints": ["Repay debt in borrowed asset", "Receive collateral + liquidation bonus (5-15%)", "Partial liquidations allowed on some protocols", "Must have capital to repay debt"]}'),
(4, 5, 'text', 'Profitability Analysis', '{"text": "Calculate liquidation profit by considering bonus, gas costs, and price impact of selling collateral.", "keyPoints": ["Profit = (Collateral × Bonus %) - Debt - Gas - Slippage", "Larger liquidations more profitable", "Consider time to sell collateral", "Account for market volatility"]}'),
(4, 6, 'text', 'Risk Management', '{"text": "Liquidation hunting carries risks including price volatility, competition, and smart contract risks.", "keyPoints": ["Collateral price may drop during execution", "Competition from other liquidators", "Gas wars can eliminate profits", "Smart contract bugs or exploits"]}');

INSERT INTO quizzes (module_id, title, passing_score, questions) VALUES
(4, 'Liquidation Expert Quiz', 80, '[
  {"id": 1, "question": "What triggers a liquidation?", "options": ["Low gas fees", "Health factor < 1.0", "High trading volume", "Validator downtime"], "correct": 1, "explanation": "Liquidations are triggered when health factor falls below 1.0."},
  {"id": 2, "question": "What is the typical liquidation bonus?", "options": ["1-2%", "5-15%", "20-30%", "50%+"], "correct": 1, "explanation": "Liquidation bonuses typically range from 5-15% of collateral value."},
  {"id": 3, "question": "How is health factor calculated?", "options": ["Collateral / Debt", "(Collateral × LT) / Debt", "Debt / Collateral", "Collateral - Debt"], "correct": 1, "explanation": "Health Factor = (Collateral Value × Liquidation Threshold) / Borrowed Value."},
  {"id": 4, "question": "What happens to the first liquidator?", "options": ["They share profits", "They get the full liquidation", "They pay a penalty", "Nothing special"], "correct": 1, "explanation": "The first liquidator to execute gets the full liquidation and bonus."},
  {"id": 5, "question": "At what health factor should you monitor positions?", "options": ["< 2.0", "< 1.5", "< 1.05", "< 0.5"], "correct": 2, "explanation": "Monitor positions with health factor < 1.05 as they''re close to liquidation."},
  {"id": 6, "question": "What do you need to execute a liquidation?", "options": ["Collateral asset", "Borrowed asset to repay debt", "Protocol governance tokens", "Validator access"], "correct": 1, "explanation": "You need the borrowed asset to repay the debt and trigger liquidation."},
  {"id": 7, "question": "What is the main risk in liquidation hunting?", "options": ["Too much profit", "Price volatility during execution", "Low competition", "High health factors"], "correct": 1, "explanation": "Price volatility can cause collateral value to drop during execution, reducing profits."}
]');

-- Module 5: Validator Selection (5 sections)
INSERT INTO module_content (module_id, section_order, section_type, title, content) VALUES
(5, 1, 'text', 'Why Validator Choice Matters', '{"text": "Choosing the right validator affects your MEV success rate, bundle execution speed, and overall profitability.", "keyPoints": ["Jito validators capture more MEV", "Validator performance affects bundle success", "Commission rates impact net returns", "Reputation matters for consistent execution"]}'),
(5, 2, 'text', 'Key Validator Metrics', '{"text": "Evaluate validators based on multiple performance metrics.", "keyPoints": ["Skip rate: Lower is better (< 5%)", "MEV rewards: Higher indicates better MEV capture", "Commission: Typical range 5-10%", "Uptime: Should be > 99%", "Stake amount: Indicates trust and reliability"]}'),
(5, 3, 'text', 'Jito vs Non-Jito Validators', '{"comparison": [{"aspect": "MEV Capture", "nonJito": "Limited", "jito": "Full", "impact": "3-5x higher bundle success"}, {"aspect": "Bundle Support", "nonJito": "No", "jito": "Yes", "impact": "Atomic execution"}, {"aspect": "Revenue", "nonJito": "Standard", "jito": "Standard + MEV tips", "impact": "5-15% higher"}], "keyPoints": ["Always prefer Jito validators for MEV", "Jito validators have higher success rates", "More competitive but worth it"]}'),
(5, 4, 'text', 'Validator Reputation', '{"text": "Validator reputation is built over time through consistent performance and fair practices.", "keyPoints": ["Check historical performance data", "Look for consistent uptime", "Verify MEV reward distribution", "Read community feedback", "Avoid validators with censorship history"]}'),
(5, 5, 'text', 'Diversification Strategy', '{"text": "Don''t rely on a single validator. Diversify submissions across multiple high-quality validators.", "keyPoints": ["Submit to 3-5 top validators", "Rotate based on recent performance", "Monitor success rates per validator", "Adjust strategy based on data"]}');

INSERT INTO quizzes (module_id, title, passing_score, questions) VALUES
(5, 'Validator Selection Quiz', 80, '[
  {"id": 1, "question": "What is a good validator skip rate?", "options": ["< 1%", "< 5%", "< 20%", "< 50%"], "correct": 1, "explanation": "A good validator skip rate is under 5%, indicating reliable block production."},
  {"id": 2, "question": "Why choose Jito validators for MEV?", "options": ["Lower fees", "Bundle support and higher success rates", "Faster blocks", "More stake"], "correct": 1, "explanation": "Jito validators support bundles and have 3-5x higher MEV success rates."},
  {"id": 3, "question": "What is typical validator commission?", "options": ["0-2%", "5-10%", "20-30%", "50%+"], "correct": 1, "explanation": "Typical validator commission ranges from 5-10% of rewards."},
  {"id": 4, "question": "How many validators should you submit bundles to?", "options": ["1 only", "3-5 validators", "10+ validators", "All validators"], "correct": 1, "explanation": "Submit to 3-5 top validators to diversify and maximize success rates."},
  {"id": 5, "question": "What uptime should a good validator have?", "options": ["> 90%", "> 95%", "> 99%", "100%"], "correct": 2, "explanation": "Good validators maintain > 99% uptime for consistent performance."},
  {"id": 6, "question": "How much more revenue do Jito validators earn?", "options": ["Same", "5-15% more", "50% more", "Double"], "correct": 1, "explanation": "Jito validators typically earn 5-15% more from MEV tips."}
]');

-- Module 6: Bundle Construction (7 sections)
INSERT INTO module_content (module_id, section_order, section_type, title, content) VALUES
(6, 1, 'text', 'Bundle Fundamentals', '{"text": "Bundles are groups of transactions that execute atomically - either all succeed or all fail. This is critical for complex MEV strategies.", "keyPoints": ["Atomic execution prevents partial failures", "Transactions execute in specified order", "Failed bundles don''t consume gas", "Enables complex multi-step strategies"]}'),
(6, 2, 'text', 'Transaction Ordering', '{"text": "The order of transactions in a bundle is critical for success. Wrong ordering can cause the entire bundle to fail.", "keyPoints": ["Dependencies must execute first", "Approvals before transfers", "Swaps before arbitrage completion", "Consider state changes between transactions"]}'),
(6, 3, 'text', 'Gas Estimation', '{"text": "Accurate gas estimation ensures your bundle has enough compute units to execute fully.", "keyPoints": ["Estimate each transaction separately", "Add 10-20% buffer for safety", "Monitor compute unit limits (1.4M per transaction)", "Higher gas = higher priority"]}'),
(6, 4, 'text', 'Bundle Tips', '{"text": "Tips incentivize validators to include your bundle. Higher tips increase inclusion probability.", "keyPoints": ["Tip based on expected profit (1-5%)", "Competitive opportunities need higher tips", "Tips go to validators, not burned", "Balance tip vs profit margin"]}'),
(6, 5, 'text', 'Error Handling', '{"text": "Bundles can fail for many reasons. Understanding failure modes helps you build robust bundles.", "keyPoints": ["Slippage tolerance too tight", "Insufficient gas", "State changes between simulation and execution", "Account data race conditions"]}'),
(6, 6, 'text', 'Simulation Testing', '{"text": "Always simulate bundles before submission to catch errors and estimate outcomes.", "keyPoints": ["Use Jito simulation API", "Test with current blockchain state", "Verify all transactions succeed", "Check final profit after costs"]}'),
(6, 7, 'text', 'Advanced Techniques', '{"text": "Professional bundle builders use advanced techniques to maximize success and profitability.", "keyPoints": ["Multi-bundle strategies for redundancy", "Dynamic tip adjustment based on competition", "State prefetching to reduce latency", "Custom priority fee strategies"]}');

INSERT INTO quizzes (module_id, title, passing_score, questions) VALUES
(6, 'Bundle Construction Quiz', 80, '[
  {"id": 1, "question": "What does atomic execution mean?", "options": ["Fast execution", "All transactions succeed or all fail", "Low gas cost", "High priority"], "correct": 1, "explanation": "Atomic execution means all transactions in the bundle succeed or all fail together."},
  {"id": 2, "question": "Why is transaction ordering important?", "options": ["For speed", "Dependencies must execute in correct order", "To save gas", "For aesthetics"], "correct": 1, "explanation": "Transaction ordering is critical because dependencies must execute before dependent transactions."},
  {"id": 3, "question": "What is a typical bundle tip percentage?", "options": ["0.1%", "1-5%", "10-20%", "50%"], "correct": 1, "explanation": "Bundle tips typically range from 1-5% of expected profit."},
  {"id": 4, "question": "What happens if one transaction in a bundle fails?", "options": ["Others still execute", "Entire bundle fails", "It retries", "Validator decides"], "correct": 1, "explanation": "If any transaction fails, the entire bundle fails atomically."},
  {"id": 5, "question": "Why simulate bundles before submission?", "options": ["Required by protocol", "To catch errors and estimate outcomes", "To save gas", "For fun"], "correct": 1, "explanation": "Simulation catches errors and estimates outcomes before spending gas on submission."},
  {"id": 6, "question": "What is the compute unit limit per transaction?", "options": ["200K", "1.4M", "10M", "Unlimited"], "correct": 1, "explanation": "Solana has a 1.4M compute unit limit per transaction."},
  {"id": 7, "question": "How much gas buffer should you add?", "options": ["0%", "10-20%", "50%", "100%"], "correct": 1, "explanation": "Add 10-20% gas buffer to account for state changes and ensure execution."},
  {"id": 8, "question": "What do bundle tips incentivize?", "options": ["Faster blocks", "Validator inclusion", "Lower fees", "More MEV"], "correct": 1, "explanation": "Tips incentivize validators to include your bundle in their blocks."},
  {"id": 9, "question": "When should you use multi-bundle strategies?", "options": ["Never", "For redundancy and higher success rates", "Only for small profits", "Always"], "correct": 1, "explanation": "Multi-bundle strategies provide redundancy and increase overall success rates."},
  {"id": 10, "question": "What causes most bundle failures?", "options": ["Low tips", "Slippage and state changes", "Validator issues", "Network congestion"], "correct": 1, "explanation": "Most bundle failures are caused by slippage tolerance and state changes between simulation and execution."}
]');

-- Module 7: Risk Management (6 sections)
INSERT INTO module_content (module_id, section_order, section_type, title, content) VALUES
(7, 1, 'text', 'MEV Risk Categories', '{"text": "MEV extraction involves multiple risk categories that can impact profitability and capital.", "keyPoints": ["Execution risk: Transaction failures", "Market risk: Price volatility", "Competition risk: Other bots", "Technical risk: Smart contract bugs", "Regulatory risk: Legal uncertainty"]}'),
(7, 2, 'text', 'Position Sizing', '{"text": "Never risk more capital than you can afford to lose. Proper position sizing protects your capital.", "keyPoints": ["Risk 1-5% of capital per opportunity", "Larger positions for higher confidence trades", "Scale position with win rate", "Keep reserve capital for opportunities"]}'),
(7, 3, 'text', 'Stop Loss Strategies', '{"text": "Set clear exit criteria to limit losses on failed strategies.", "keyPoints": ["Maximum loss per trade", "Daily loss limits", "Strategy performance thresholds", "Automatic shutdown on anomalies"]}'),
(7, 4, 'text', 'Diversification', '{"text": "Don''t rely on a single MEV strategy. Diversify across multiple opportunity types.", "keyPoints": ["Mix arbitrage, liquidations, and other strategies", "Trade multiple token pairs", "Use multiple DEXs", "Spread across time periods"]}'),
(7, 5, 'text', 'Monitoring and Alerts', '{"text": "Continuous monitoring helps you catch issues before they become costly.", "keyPoints": ["Track success rates by strategy", "Monitor gas costs vs profits", "Set alerts for anomalies", "Review performance daily"]}'),
(7, 6, 'text', 'Risk-Adjusted Returns', '{"text": "Evaluate strategies based on risk-adjusted returns, not just absolute profits.", "keyPoints": ["Sharpe Ratio: Return per unit of risk", "Maximum drawdown: Largest loss period", "Win rate: Percentage of profitable trades", "Profit factor: Gross profit / Gross loss"]}');

INSERT INTO quizzes (module_id, title, passing_score, questions) VALUES
(7, 'Risk Management Quiz', 80, '[
  {"id": 1, "question": "What percentage of capital should you risk per trade?", "options": ["10-20%", "1-5%", "50%", "100%"], "correct": 1, "explanation": "Risk 1-5% of capital per opportunity to protect against losses."},
  {"id": 2, "question": "What is execution risk?", "options": ["Market volatility", "Transaction failures", "Competition", "Regulations"], "correct": 1, "explanation": "Execution risk is the risk of transaction failures consuming gas without profit."},
  {"id": 3, "question": "Why diversify MEV strategies?", "options": ["For fun", "To reduce risk concentration", "Required by law", "Increases gas costs"], "correct": 1, "explanation": "Diversification reduces risk by not relying on a single strategy or market condition."},
  {"id": 4, "question": "What is the Sharpe Ratio?", "options": ["Total profit", "Return per unit of risk", "Win rate", "Gas efficiency"], "correct": 1, "explanation": "Sharpe Ratio measures return per unit of risk, helping compare strategies."},
  {"id": 5, "question": "When should you stop a losing strategy?", "options": ["Never", "When it hits predefined loss limits", "After 1 loss", "When profitable"], "correct": 1, "explanation": "Stop strategies when they hit predefined loss limits to protect capital."},
  {"id": 6, "question": "What is maximum drawdown?", "options": ["Highest profit", "Largest loss period", "Average loss", "Total losses"], "correct": 1, "explanation": "Maximum drawdown is the largest peak-to-trough decline in capital."},
  {"id": 7, "question": "How often should you review performance?", "options": ["Never", "Daily", "Yearly", "Only when losing"], "correct": 1, "explanation": "Review performance daily to catch issues early and optimize strategies."},
  {"id": 8, "question": "What is profit factor?", "options": ["Total profit", "Gross profit / Gross loss", "Win rate", "Average profit"], "correct": 1, "explanation": "Profit factor is gross profit divided by gross loss, showing overall profitability."}
]');
